apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-web
  namespace: lab-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-web
  template:
    metadata:
      labels:
        app: lab-web
    spec:
      containers:
        - name: lab-web
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: lab-web-html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: lab-web-html-volume
          configMap:
            name: lab-web-html
